import type { ApiDefinition } from "../types/domain.js";
const definitions: ApiDefinition[] = [
  { id: "customer-search", name: "Customer Service", description: "Finds customers by company name.", endpoint: "/api/mock/customers/search", method: "GET", requiredInputs: ["q"], optionalInputs: [], keywords: ["customer", "owned", "lufthansa", "airbus", "klm"], dependencies: [], outputSchema: "Customer[]" },
  { id: "fleet-by-customer", name: "Fleet Service", description: "Lists aircraft owned by one customer.", endpoint: "/api/mock/fleet/customer/:customerId", method: "GET", requiredInputs: ["customerId"], optionalInputs: [], keywords: ["aircraft", "fleet", "owned", "planes"], dependencies: ["customer-search"], outputSchema: "Aircraft[]" },
  { id: "fleet-all", name: "Fleet Service", description: "Lists every aircraft in the fleet.", endpoint: "/api/mock/fleet", method: "GET", requiredInputs: [], optionalInputs: [], keywords: ["fleet", "summary", "all aircraft"], dependencies: [], outputSchema: "Aircraft[]" },
  { id: "aircraft-detail", name: "Aircraft Service", description: "Gets an aircraft record.", endpoint: "/api/mock/aircraft/:id", method: "GET", requiredInputs: ["id"], optionalInputs: [], keywords: ["aircraft", "details"], dependencies: [], outputSchema: "Aircraft" },
  { id: "maintenance-by-aircraft", name: "Maintenance Service", description: "Gets maintenance records for an aircraft.", endpoint: "/api/mock/maintenance/:aircraftId", method: "GET", requiredInputs: ["aircraftId"], optionalInputs: [], keywords: ["maintenance", "under maintenance", "service"], dependencies: ["fleet-all"], outputSchema: "Maintenance[]" },
  { id: "deliveries-by-customer", name: "Delivery Service", description: "Gets deliveries for a customer.", endpoint: "/api/mock/deliveries/customer/:customerId", method: "GET", requiredInputs: ["customerId"], optionalInputs: [], keywords: ["delivery", "deliveries", "delivery schedule"], dependencies: ["customer-search"], outputSchema: "Delivery[]" }
];
export class ApiRegistry { list(): ApiDefinition[] { return definitions; } find(id: string): ApiDefinition | undefined { return definitions.find((definition) => definition.id === id); } search(words: string[]): ApiDefinition[] { return definitions.filter((definition) => words.some((word) => definition.keywords.includes(word.toLowerCase()))); } }
